version: '3.1'

services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/devapp
    ports:
      - '3000:3000'
    command: yarn dev
    volumes:
      - .:/app/
      - /app/node_modules

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
